spring:
  application:
    name: BookMyShow

  datasource:
    url: jdbc:mysql://localhost:3306/bookmyshow
    username: root
    password: Prudhviraj@852
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # Options: none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

